# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIOperater' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIOperater

  target 'UIOperaterUITests' do
    # Pods for testing
    pod 'PerformanceMonitoriOS', :git => 'http://git.woa.com/PerformancePlatform/PerformanceMonitoriOS.git', :modular_headers => true
  end

end
